--- RBAC ---
-- ACTIONS
create type public.resource_actions_enum as enum ('select', 'insert', 'update', 'delete');

--- RESOURCES
create table
  public.resources (
    id bigint generated by default as identity primary key,
    resource_name text not null unique,
    parent_id bigint references public.resources (id) on delete cascade
  );

-- ROLES
create table
  public.roles (
    id uuid primary key default gen_random_uuid (),
    role_name text not null unique
  );

--PERMISSIONS
create table
  public.permissions (
    id bigint generated by default as identity primary key,
    resource_id bigint not null references public.resources (id) on delete cascade,
    resource_action resource_actions_enum not null,
    permissions_description text,
    allow_cascade boolean default false,
    unique (resource_id, resource_action)
  );

--- ROLE_PERMISSIONS
create table
  public.role_permissions (
    id bigint generated by default as identity primary key,
    role_id uuid not null references public.roles (id) on delete cascade,
    permission_id bigint not null references public.permissions (id) on delete cascade,
    allow_wildcard boolean default false,
    unique (role_id, permission_id)
  );

-- USER ROLES
create table
  public.user_roles (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    role_id uuid not null references public.roles (id) on delete cascade,
    unique (user_id, role_id)
  );